# -*- coding: utf-8 -*-
"""lab_09_svm.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uee7CQ8YQn6sF_LHzn8Dn6Vs7sYU9yUs

# SVM

Loading the dataset
"""

from sklearn import datasets

cancer = datasets.load_breast_cancer()

"""### Data exploration

Printing the features and the labels
"""

print("Features: ", cancer.feature_names)

print("Labels: ", cancer.target_names)

"""Printing the shape"""

cancer.data.shape

"""Top 5 records"""

print(cancer.data[0:5])

"""Labels"""

print(cancer.target)

"""### Training

Train-test splitting
"""

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(cancer.data, cancer.target, test_size=0.3,random_state=109) # 70% training and 30% test

from sklearn import svm

clf = svm.SVC(kernel='linear') # Linear Kernel

clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)

"""### Evaluation

Accuracy calculation
"""

from sklearn import metrics

print("Accuracy:", metrics.accuracy_score(y_test, y_pred))

"""Precision and recall"""

print("Precision:",metrics.precision_score(y_test, y_pred))

print("Recall:",metrics.recall_score(y_test, y_pred))